name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci && cd functions && npm ci

      - name: Build functions
        run: cd functions && npm run build

      - name: Run tests
        run: npm run test:ci
