name: Deploy
'on':
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && cd functions && npm ci && cd .. && npm run build:prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KRAMSTERAPP }}'
          channelId: live
          projectId: kramsterapp
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
